In [1]:
# Nilesh Kale (AI3005)

# Creating Array of fibonacci series Manually

n=int(input("Enter a number: "))
a=0
b=1
l=[]
l.append(a)
l.append(b)
for i in range(n):
    c=a+b
    l.append(c)
    a=b
    b=c
print(l)

Enter a number: 4
[0, 1, 1, 2, 3, 5]


In [2]:
# Manually Addition of Matrix
def add_matrices (matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        print("Matrices cannot be added as they have different dimensions.")
        return None

     #Initialize the result matrix with the same dimensions
    result_matrix = [[0 for _ in range(len(matrix1[0]))] for _ in range(len(matrix1))]

    #Perform matrix addition

    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result_matrix[i][j] = matrix1[i][j]+ matrix2[i][j]

    return result_matrix

# Example usage:
matrix1 = [[3, 7, 9],
           [6, 1, 3],
           [7, 8, 9]]
matrix2 = [[9, 8, 3],
           [6, 7, 8],
           [3, 6, 9]]

result= add_matrices (matrix1, matrix2)
if result:
    print("Resultant Matrix:")
    for row in result:
        print(row)

Resultant Matrix:
[12, 15, 12]
[12, 8, 11]
[10, 14, 18]


In [3]:
#pr. 2 theory on np and pd

import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
# Arithmetic operation
print(s + 2)

# Aggregation operation
print("mean\n",s.mean())

# Finding missing data
print("Missing values\n", s.isnull())
# Handle missing data
print("Handling Missing values\n", s.fillna(0))
s= s.fillna(0)
# Sorting
print("Sorting values\n",s.sort_values())

0     3.0
1     5.0
2     7.0
3     NaN
4     8.0
5    10.0
dtype: float64
mean
 4.6
Missing values
 0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool
Handling Missing values
 0    1.0
1    3.0
2    5.0
3    0.0
4    6.0
5    8.0
dtype: float64
Sorting values
 3    0.0
0    1.0
1    3.0
2    5.0
4    6.0
5    8.0
dtype: float64


In [6]:
# Apply function
print("Applying Lamda Functions\n",s.apply(lambda x: x**2))
# Statistical functions
print("Statistical values\n",s.cumsum())
# Describe
print("Description\n",s.describe())

Applying Lamda Functions
 0     1.0
1     9.0
2    25.0
3     0.0
4    36.0
5    64.0
dtype: float64
Statistical values
 0     1.0
1     4.0
2     9.0
3     9.0
4    15.0
5    23.0
dtype: float64
Description
 count    6.000000
mean     3.833333
std      3.060501
min      0.000000
25%      1.500000
50%      4.000000
75%      5.750000
max      8.000000
dtype: float64


In [7]:
# Creating a DataFrame
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [24, 27, 22, 32],
'Score': [85.5, 90.0, 78.5, 88.0]
}
df = pd.DataFrame(data)
# Display the DataFrame
print("DataFrame:\n", df)

DataFrame:
       Name  Age  Score
0    Alice   24   85.5
1      Bob   27   90.0
2  Charlie   22   78.5
3    David   32   88.0


In [8]:
# Basic operations
print("\nSummary statistics:\n", df.describe())
print("\nColumn Names:\n", df.columns)


Summary statistics:
              Age      Score
count   4.000000   4.000000
mean   26.250000  85.500000
std     4.349329   5.016639
min    22.000000  78.500000
25%    23.500000  83.750000
50%    25.500000  86.750000
75%    28.250000  88.500000
max    32.000000  90.000000

Column Names:
 Index(['Name', 'Age', 'Score'], dtype='object')


In [9]:
print("\nFirst Four rows:\n", df.head(4))


First Four rows:
       Name  Age  Score
0    Alice   24   85.5
1      Bob   27   90.0
2  Charlie   22   78.5
3    David   32   88.0


In [10]:
df['Top Score'] = df['Score'] >= 85
print("\nDataFrame with Top Score column:\n", df)


DataFrame with Top Score column:
       Name  Age  Score  Top Score
0    Alice   24   85.5       True
1      Bob   27   90.0       True
2  Charlie   22   78.5      False
3    David   32   88.0       True


In [11]:
top_scorers = df[df['Top Score']]['Name']
print("\nStudents with top scores:\n", top_scorers)


Students with top scores:
 0    Alice
1      Bob
3    David
Name: Name, dtype: object


In [12]:
sorted_df = df.sort_values(by='Score', ascending=False)
print("\nDataFrame sorted by Score in descending order:\n", sorted_df)


DataFrame sorted by Score in descending order:
       Name  Age  Score  Top Score
1      Bob   27   90.0       True
3    David   32   88.0       True
0    Alice   24   85.5       True
2  Charlie   22   78.5      False


In [13]:
# Filling missing values with the mean percentage
df['Score'].fillna(df['Score'].mean(), inplace=True)
print("\nDataFrame with missing value filled:\n", df)


DataFrame with missing value filled:
       Name  Age  Score  Top Score
0    Alice   24   85.5       True
1      Bob   27   90.0       True
2  Charlie   22   78.5      False
3    David   32   88.0       True


/tmp/ipython-input-3355374703.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(df['Score'].mean(), inplace=True)


In [14]:
df['Age Group'] = df['Age'].apply(lambda x: 'Under 25' if x < 25 else '25 and above')
print("\nDataFrame with Age Group column:\n", df)


DataFrame with Age Group column:
       Name  Age  Score  Top Score     Age Group
0    Alice   24   85.5       True      Under 25
1      Bob   27   90.0       True  25 and above
2  Charlie   22   78.5      False      Under 25
3    David   32   88.0       True  25 and above


In [15]:
mean_score_by_age_group = df.groupby('Age Group')['Score'].mean()
print("\nMean Score by Age Group:\n", mean_score_by_age_group)


Mean Score by Age Group:
 Age Group
25 and above    89.0
Under 25        82.0
Name: Score, dtype: float64


In [16]:
name_score_df = df[['Name', 'Score']]
print("\nName and Score columns:\n", name_score_df)


Name and Score columns:
       Name  Score
0    Alice   85.5
1      Bob   90.0
2  Charlie   78.5
3    David   88.0


In [17]:
df = df.drop(columns=['Top Score'])
print("\nDataFrame after dropping 'Top Score' column:\n", df)


DataFrame after dropping 'Top Score' column:
       Name  Age  Score     Age Group
0    Alice   24   85.5      Under 25
1      Bob   27   90.0  25 and above
2  Charlie   22   78.5      Under 25
3    David   32   88.0  25 and above


In [18]:
data = {

'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace','Hannah'],
'Roll No': [1, 2, 3, 4, 5, 6, 7, 8],
'Address': ['123 Maple St', '456 Oak St', '789 Pine St', np.nan, '202 CedarSt', '303 Elm St', np.nan, '505 Walnut St'],
'Age': [20, 21, np.nan, 22, 20, 21, 19, 22],
'Percentage': [85, np.nan, 78, 88, 95, 70, 82, np.nan],
'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F']
}

In [19]:
df = pd.DataFrame(data)

In [20]:
# Select specific columns
selected_columns = df[['Name', 'Roll No']]
print(selected_columns)

      Name  Roll No
0    Alice        1
1      Bob        2
2  Charlie        3
3    David        4
4      Eve        5
5    Frank        6
6    Grace        7
7   Hannah        8


In [21]:

#1. Create 2-D matrices using NumPy.
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [5, 4, 3]])
print("1st 2D Array:\n", arr1)
print("2nd 2D Array:\n", arr2)

print("----------------------------")

# 2. Verify the conditions for matrix addition.
if np.shape(arr1)==np.shape(arr2):
    print("we can make addition of the matrics")
else:
    print("we can not make addition of the matrics")
print("----------------------------")

# 3. Perform matrix addition.
res=arr1+arr2
print("Addition is:\n",res)
print("----------------------------")

# 4. Compute the transpose of one of your matrices and perform matrix multiplication with its
# original matrix.
a=np.array([[1,2,3],[4 , 5, 6],[7, 8, 9]])
trn_a=np.transpose(a)
print("Multiplication is:\n",np.multiply(a,trn_a))

1st 2D Array:
 [[1 2 3]
 [4 5 6]]
2nd 2D Array:
 [[7 8 9]
 [5 4 3]]
----------------------------
we can make addition of the matrics
----------------------------
Addition is:
 [[ 8 10 12]
 [ 9  9  9]]
----------------------------
Multiplication is:
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


In [22]:
# Q.2 Sales Data Analysis

sales_data = np.array([
    [1200, 1500, 1300, 1100], # Product 1 sales
    [800, 950, 1000, 1200], # Product 2 sales
    [1400, 1600, 1700, 1800], # Product 3 sales
    [900, 800, 850, 950] # Product 4 sales
])

# 1. Calculate the average sales for each product.
avg = np.mean(sales_data, axis=1)
print("Average sales for Each Product:\n", avg)
print("----------------------------")

# 2. Determine the highest and lowest sales figures for each product.
high_sale= np.max(sales_data, axis=1)
low_sale= np.min(sales_data, axis=1)
print("Highest sale for each product is:\n", high_sale)
print("Lowest sale for each product is:\n", low_sale)
print("----------------------------")

# 3. Compute the overall average sales across all products.
overall_average = np.mean(sales_data)
print("Overall Average sales:\n", overall_average)
print("----------------------------")

# 4. Make threshold sales >1000, show how many of them are above and below the threshold
threshold = 1000
above_threshold = np.all(sales_data > threshold, axis=1)
print("Product who sales above the threshold:\n ",above_threshold)
print("----------------------------")

Average sales for Each Product:
 [1275.   987.5 1625.   875. ]
----------------------------
Highest sale for each product is:
 [1500 1200 1800  950]
Lowest sale for each product is:
 [1100  800 1400  800]
----------------------------
Overall Average sales:
 1190.625
----------------------------
Product who sales above the threshold:
  [ True False  True False]
----------------------------


In [23]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace','Hannah'],
    'Roll No': [1, 2, 3, 4, 5, 6, 7, 8],
    'Address': ['123 Maple St', '456 Oak St', '789 Pine St', np.nan, '202 CedarSt', '303 Elm St', np.nan, '505 Walnut St'],
    'Age': [20, 21, np.nan, 22, 20, 21, 19, 22],
    'Percentage': [85, np.nan, 78, 88, 95, 70, 82, np.nan],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F']
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)
print("----------------------------")

# 1. Display the first five rows of the DataFrame.
print("\nFirst five rows:\n", df.head(5))
print("----------------------------")

# 2. Display the data types of each column.
print(df.dtypes)
print("----------------------------")

# 3. Handle missing values by: Filling numerical values with the mean. Filling missing address values with “Unknown”.
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Percentage'].fillna(df['Percentage'].mean(), inplace=True)
df['Address'].fillna('Unknown', inplace=True)
print("\nHandling Missing values:\n",df)
print("----------------------------")


# 4. Calculate the mean age and mean percentage of the students.
print("\nthe mean age is:", df['Age'].mean())
print("the mean percentage is:", df['Percentage'].mean())
print("----------------------------")

# 5. Add a column Pass which is True if the student’s percentage is 75 or above, otherwise False.
df['Pass']= df['Percentage'].apply(lambda x: True if x>=75 else False)
print("\nDataFrame with Pass column:\n", df)
print("----------------------------")


# 6. Filter the DataFrame to show only the students who have passed.
passed_students = df[df['Percentage'] > 75]
print("Passed Student:\n",passed_students)
print("----------------------------")

# 7. Group the DataFrame by Gender and calculate the average percentage for each group.
avg_per_by_gen = df.groupby('Gender')['Percentage'].mean()
print("\nAverage Percentage by Gender:\n",avg_per_by_gen)
print("----------------------------")


# 8. Sort the DataFrame by Percentage in descending order.
sorted_df= df.sort_values(by='Percentage', ascending=False)
print("\nDataFrame by Percentage in descending order:\n",sorted_df)
print("----------------------------")


# 9. Create a new column ‘Age Group’ with values ‘Under 21’ and ‘21 and above’.
df['Age Group']= df['Age'].apply( lambda x: 'Under 21' if x<21 else '21 and above')
print("\ndataframe after a new column ‘Age Group’")
print("----------------------------")

# 10. Drop the column Pass
df= df.drop(columns=['Pass'])
print("\nDataframe after droping 'Pass' column:\n",df)
print("----------------------------")


DataFrame:
       Name  Roll No        Address   Age  Percentage Gender
0    Alice        1   123 Maple St  20.0        85.0      F
1      Bob        2     456 Oak St  21.0         NaN      M
2  Charlie        3    789 Pine St   NaN        78.0      M
3    David        4            NaN  22.0        88.0      M
4      Eve        5    202 CedarSt  20.0        95.0      F
5    Frank        6     303 Elm St  21.0        70.0      M
6    Grace        7            NaN  19.0        82.0      F
7   Hannah        8  505 Walnut St  22.0         NaN      F
----------------------------

First five rows:
       Name  Roll No       Address   Age  Percentage Gender
0    Alice        1  123 Maple St  20.0        85.0      F
1      Bob        2    456 Oak St  21.0         NaN      M
2  Charlie        3   789 Pine St   NaN        78.0      M
3    David        4           NaN  22.0        88.0      M
4      Eve        5   202 CedarSt  20.0        95.0      F
----------------------------
Name           ob

/tmp/ipython-input-4137992178.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipython-input-4137992178.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try 